name: Run Tests

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  test:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Create and activate venv
      run: |
        python -m venv venv
        source venv/bin/activate
    
    - name: Install dependencies (via pip)
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install jq (if needed)
      run: |
        if ! command -v jq &> /dev/null; then
          echo "jq not found, trying to install..."
          sudo apt-get update && sudo apt-get install -y jq || echo "Warning: jq installation failed"
        fi
    
    - name: Run Flask app in background
      run: |
        source venv/bin/activate
        python app.py &
        echo $! > app.pid
        sleep 5  
    
    - name: Run tests
      run: |
        source venv/bin/activate
        chmod +x test/test.sh
        ./test/test.sh
    
    - name: Stop Flask app (cleanup)
      if: always()  
      run: |
        if [ -f app.pid ]; then
          kill $(cat app.pid) || true
          rm app.pid
        fi
