name: Run Tests

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  test:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt-get update && sudo apt-get install -y jq

    - name: Run application
      run: |
        python app.py &
        echo $! > server.pid
        sleep 5

    - name: Verify server is running
      run: |
        curl --retry 3 --retry-delay 2 http://localhost:5000/time

    - name: Run tests
      run: |
        chmod +x test/test.sh
        ./test/test.sh

    - name: Stop application
      if: always()
      run: |
        if [ -f server.pid ]; then
          kill $(cat server.pid) || true
          rm server.p
